apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: consultant-plus-prod

bases:
  - ../../helm/consultant-plus

images:
  - name: ghcr.io/zdestr/cp-pipeline
    newTag: 1.0.0
