apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: consultant-plus-dev

bases:
  - ../../helm/consultant-plus

patches:
  - path: executor-patch.yaml

images:
  - name: registry.internal/consultant-plus/cp-pipeline
    newTag: dev-latest
