apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: consultant-plus-staging


patches:
- path: executor-patch.yaml

images:
- name: ghcr.io/zdestr/cp-pipeline
  newTag: 4b1ad81e
resources:
- ../../helm/consultant-plus
