apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: consultant-plus-staging

bases:
  - ../../helm/consultant-plus

patches:
  - path: executor-patch.yaml

images:
  - name: ghcr.io/zdestr/cp-pipeline
    newTag: latest
